/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.evernote.edam.userstore;

/**
 * Enumeration of Sponsored Group Roles
 */
public class SponsoredGroupRole implements org.apache.thrift.TEnum {

  public static final SponsoredGroupRole GROUP_MEMBER = new SponsoredGroupRole(1);
  public static final SponsoredGroupRole GROUP_ADMIN = new SponsoredGroupRole(2);
  public static final SponsoredGroupRole GROUP_OWNER = new SponsoredGroupRole(3);

  private final int value;

  private SponsoredGroupRole(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static SponsoredGroupRole findByValue(int value) { 
    switch (value) {
      case 1:
        return GROUP_MEMBER;
      case 2:
        return GROUP_ADMIN;
      case 3:
        return GROUP_OWNER;
      default:
        return null;
    }
  }
}
